controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    mobile_base_controller:
      type: diff_drive_controller/DiffDriveController

    range_broadcaster:
      type: range_sensor_broadcaster/RangeSensorBroadcaster

    filtered_range_broadcaster:
      type: range_sensor_broadcaster/RangeSensorBroadcaster

    range_filter:
      type: workshop_controllers/ChainedFilter


head_controller:
  ros__parameters:
    joints:
      - head_1_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 5.0
      head_1_joint:
        goal: 0.5

mobile_base_controller:
  ros__parameters:
    use_stamped_vel: False
    left_wheel_names  :
      - wheel_left_joint
    right_wheel_names :
      - wheel_right_joint

    wheel_radius: 0.0985
    wheel_separation: 0.4044

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Publish limited velocity
    publish_cmd: true

    # Publish wheel data
    publish_wheel_data: true

range_broadcaster:
  ros__parameters:
    # Setting mandatory parameters
    sensor_name: "range_sensor"
    frame_id: "base_sonar01_link"

    # Setting parameters with changed default value to check those are used
    radiation_type: 1
    field_of_view: 0.1
    min_range: 0.10
    max_range: 7.0
    variance: 1.0


range_filter:
  ros__parameters:
    input_interface: "range_sensor/range"

    output_interface: "range"

    filter_chain:
      filter1:
        type: "filters/MedianFilterDouble"
        name: "median_filter"
        params:
          number_of_observations: 5

filtered_range_broadcaster:
  ros__parameters:
    # Setting mandatory parameters
    sensor_name: "range_filter"
    frame_id: "base_sonar01_link"
