services:
  dev:
    image: bmagyar/roscon2024_workshop
    build:
      context: .
      dockerfile: docker/Dockerfile
    network_mode: host
    init: true
    environment:
      # Wall off ROS. When this is FALSE, ROS_DOMAIN_ID is important to set
      - ROS_AUTOMATIC_DISCOVERY_RANGE=localhost
      # Settings to make graphical programs work
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      # Settings to make graphical programs work
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - /dev/dri:/dev/dri
    # this adds docker -it
    working_dir: /home/ros/ws
    stdin_open: true # docker run -i
    tty: true        # docker run -t
